### ISSUE TITLE
v1.1.1 breaks v1.0.2 and violates semver

### ISSUE THREAD

**Issue by cryptopapi997** [otter-sec/anchor#4725]
Any program that uses `declare_program!` with anchor_lang 1.0.2 is now broken because anchor_lang 1.0.2 doesn't specify that these packages

```
anchor-attribute-access-control 
anchor-attribute-account 
anchor-attribute-constant 
anchor-attribute-error 
anchor-attribute-event 
anchor-attribute-program 
anchor-derive-accounts 
anchor-derive-serde 
anchor-derive-space 
anchor-syn 
```

also have to be 1.0.2 (i.e. version = "=1.0.2") and instead just allows any version greater than 1.0.2 (i.e. version = "1.0.2") for these, which leads to this error

```
error[E0412]: cannot find type `CpiReturnData` in module `anchor_lang::__private`
 --> src/lib.rs:3:1
  |
3 | declare_program!(my_prog);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `anchor_lang::__private`
  |
  = note: this error originates in the macro `declare_program` (in Nightly builds, run with -Z macro-backtrace for more info)
```

when trying to compile anything with `declare_program!`. I have an MRE here: https://github.com/cryptopapi997/anchor-semver-vio-mre

I see three main ways of fixing this:

- a) release 0.10.3 which is the same as 0.10.2 but adds "=1.0.2" instead of just "1.0.2" for these crates. This wouldn't fix the semver violation per se, but it would unblock us, since the migration from 1.0.2 to 1.1.1 isn't super trivial for us so if we can stick to what is effectively 1.0.2 without this being broken that would solve our problem at least
- b) release 1.1.2 that fixes this semver violation
- c) yank 1.1.1 and re-release it as 2.x

**Comment by jacobcreech** [comment]
Could we also yank 1.1.1 and release 1.1.2 that fixes?

**Comment by chen-robert** [comment]
Appreciate the report @cryptopapi997, we will fix this ASAP. As a temporary workaround for others, consider pinning the versions in your Cargo.toml

```
anchor-attribute-access-control = "=1.0.2"
anchor-attribute-account = "=1.0.2"
anchor-attribute-constant = "=1.0.2"
anchor-attribute-error = "=1.0.2"
anchor-attribute-event = "=1.0.2"
anchor-attribute-program = "=1.0.2"
anchor-derive-accounts = "=1.0.2"
anchor-derive-serde = "=1.0.2"
anchor-derive-space = "=1.0.2"
anchor-syn = "=1.0.2"
```

**Comment by cryptopapi997** [comment]
Yes, this is what I did so far. Thanks for the quick response & turnaround!

**Comment by jamie-osec** [comment]
1.0.3 and 1.1.2 are out with this fix.
