### ISSUE TITLE
anchor-derive-serde 1.0.2 requires Rust 1.87 due to Vec::extract_if

### ISSUE THREAD

**Issue by rista404** [otter-sec/anchor#4621]
`anchor-derive-serde 1.0.2` does not compile on Rust 1.86 because it uses `Vec::extract_if`, which was stabilized in Rust 1.87. it errors out with:

```text
  error[E0658]: use of unstable library feature `extract_if`: recently added
    --> anchor-derive-serde-1.0.2/src/lib.rs:25:10
     |
  25 |         .extract_if(.., |attr| attr.path.is_ident("borsh"))
     |          ^^^^^^^^^^
     |
     = note: see issue #43244 <https://github.com/rust-lang/rust/issues/43244> for more information
```

The `extract_if` should be easy to replace with stable APIs compatible with Rust 1.86. Happy to open a PR!

**Comment by jamie-osec** [comment]
Closing as our MSRV is 1.89 (corresponding to platform-tools 1.52). If you use an up-to-date Anchor/Solana installation, this should be handled automatically. We'll formalize this with a `rust-version` key in `anchor-lang`
