### PR TITLE
chore(lang): Pin Rust version to 1.89 in lang/Cargo.toml

### LINKED ISSUE #4621: anchor-derive-serde 1.0.2 requires Rust 1.87 due to Vec::extract_if
`anchor-derive-serde 1.0.2` does not compile on Rust 1.86 because it uses `Vec::extract_if`, which was stabilized in Rust 1.87. it errors out with:

```text
  error[E0658]: use of unstable library feature `extract_if`: recently added
    --> anchor-derive-serde-1.0.2/src/lib.rs:25:10
     |
  25 |         .extract_if(.., |attr| attr.path.is_ident("borsh"))
     |          ^^^^^^^^^^
     |
     = note: see issue #43244 <https://github.com/rust-lang/rust/issues/43244> for more information
```

The `extract_if` should be easy to replace with stable APIs compatible with Rust 1.86. Happy to open a PR!

### PR DESCRIPTION
**Pull request by swaroop-osec**
Fixes #4621

### CODE REVIEW

File: CHANGELOG.md [hunk 1]
```diff
@@ -30,6 +30,7 @@ The minor version will be incremented upon a breaking change and the patch versi
 
 ### Fixes
 
+- lang: Pin `rust-version = "1.89"` on `anchor-lang` so consumers on older toolchains get a clear cargo error instead of a transitive `extract_if` E0658 ([#4638](https://github.com/otter-sec/anchor/pull/4638)).
```
Comment (jamie-osec) [inline CHANGELOG.md]:
```suggestion
- lang: Set `anchor-lang` Minimum Supported Rust Version to `1.89` ([#4638](https://github.com/otter-sec/anchor/pull/4638)).
```

**Review by jamie-osec — APPROVED** [review]
